language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts: ${ssh_addr}
branches:
  only:
  - sources
script:
- git config user.name "${GH_NAME}"
- git config user.email "${GH_EMAIL}"
- npm install && npm run build && npm run publish
- tar zcvf blog.tgz public/ && scp -P ${ssh_port} blog.tgz "${ssh_user}@${ssh_addr}:~/" && ssh -p ${ssh_port} "${ssh_user}@${ssh_addr}" ./deploy-blog.sh
before_install:
- openssl aes-256-cbc -K $encrypted_515509610fb8_key -iv $encrypted_515509610fb8_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
