language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts: 47.96.136.135
branches:
  only:
  - sources
script:
- git config user.name "${GH_NAME}"
- git config user.email "${GH_EMAIL}"
- npm install && npm run build && npm run publish
- bash ./deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_515509610fb8_key -iv $encrypted_515509610fb8_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- SSH_PORT=${ssh_port}
- SSH_USER=${ssh_user}
- SSH_ADDR=${ssh_addr}
