# .travis.yml
language: node_js
node_js:
  - '8'
branches:
  only:
    - source
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - npm install && npm run build && npm run publish
